plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  index.md

theme: jekyll-theme-cayman
title: Graduate School and Mental Health
description: Implications for UCSD's Bioinformatics & Systems Biology program